# Generated by Django 4.1.7 on 2023-04-05 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='booked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realapp.listing')),
            ],
        ),
    ]
