# Generated by Django 4.1.7 on 2023-04-05 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realapp', '0002_booked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booked',
            old_name='Id',
            new_name='SalePrice',
        ),
    ]
